import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ReduxProvider } from "@/lib/ReduxProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job portal 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black `}>
        <ReduxProvider>
          <main className="relative">
            <div className="sticky bg-black top-0 z-50 w-full">
              <Navbar />
            </div>
            {children}
          </main>
        </ReduxProvider>
        <Toaster />
      </body>
    </html>
  );
}
